spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplacedemo
    username: demouser
    password: '1234554321'
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  thymeleaf:
    encoding: UTF-8
    cache: false
    check-template: true
    check-template-location: true

logging.level.org.springframework.web: error
logging.level.org.hibernate: info
logging.level.com.example.marketplacedemo: debug
#server:
#  port: 80
